version: '3.8'

services:
  # Central Database (Tenant metadata)
  central-db:
    image: postgres:15
    environment:
      POSTGRES_DB: central_tenant_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - central_db_data:/var/lib/postgresql/data
    networks:
      - lda-network

  # Redis for caching
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - lda-network

  # Azure Storage Emulator (Azurite)
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    ports:
      - "10000:10000"  # Blob
      - "10001:10001"  # Queue
      - "10002:10002"  # Table
    networks:
      - lda-network

  # Temporal PostgreSQL (for Temporal's internal state)
  temporal-postgresql:
    image: postgres:15
    environment:
      POSTGRES_DB: temporal
      POSTGRES_USER: temporal
      POSTGRES_PASSWORD: temporal
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5433:5432"  # Different port to avoid conflict with central-db
    volumes:
      - temporal_db_data:/var/lib/postgresql/data
    networks:
      - lda-network

  # Temporal Server
  temporal:
    image: temporalio/auto-setup:latest
    environment:
      DB: postgres12
      DB_PORT: 5432
      POSTGRES_USER: temporal
      POSTGRES_PWD: temporal
      POSTGRES_SEEDS: temporal-postgresql
    ports:
      - "7233:7233"
    depends_on:
      - temporal-postgresql
    networks:
      - lda-network

  # Temporal Web UI
  temporal-web:
    image: temporalio/web:latest
    environment:
      TEMPORAL_GRPC_ENDPOINT: temporal:7233
      TEMPORAL_PERMIT_WRITE_API: true
    ports:
      - "8088:8088"
    depends_on:
      - temporal
    networks:
      - lda-network

volumes:
  central_db_data:
  temporal_db_data:

networks:
  lda-network:
    driver: bridge 