[development]
# Development environment overrides
debug = true
log_level = "DEBUG"

# Central tenant database
[development.central_db]
host = "localhost"
port = 5432
database = "central_tenant_db"
username = "postgres"
password = "postgres"
connection_string = "postgresql://postgres:postgres@localhost:5432/central_tenant_db"

# Tenant database configuration
[development.tenant_db]
host = "localhost"
port = 5432
username = "postgres"
password = "postgres"
database_prefix = "tenant_"
database_suffix = "_db"

# External services
[development.pinecone]
api_key = "pcsk_AELmV_A35kCzSgERmVA7tr6USXQP49fD63Xos9Xp87LmsYj2fGFK3mqvzFF1WZMSKi6oW"
environment = "us-east-1"
index_prefix = "tenant-"
index_suffix = "-index"

[development.pinecone.indexes]
# Tenant-specific indexes will be created dynamically
# gazdecki-consortium = "tenant-gazdecki-consortium-index"

[development.azure]
# For local development, we'll use Azurite or Azure Storage Emulator
use_emulator = true
emulator_connection_string = "DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://127.0.0.1:10000/devstoreaccount1;QueueEndpoint=http://127.0.0.1:10001/devstoreaccount1;TableEndpoint=http://127.0.0.1:10002/devstoreaccount1;"

# For real Azure (when not using emulator)
service_bus_connection_string = "dev-service-bus-connection"
storage_connection_string = "DefaultEndpointsProtocol=https;AccountName=YOUR_BASE_STORAGE_ACCOUNT;AccountKey=YOUR_STORAGE_ACCOUNT_KEY;EndpointSuffix=core.windows.net"
tenant_id = "your-azure-tenant-id"
client_id = "your-azure-client-id"
certificate_path = "path/to/your/certificate.pem"
base_storage_account = "YOUR_BASE_STORAGE_ACCOUNT"

[development.azure.storage_accounts]
# Tenant-specific storage accounts will be created dynamically
# Pattern: tenant-{tenant-slug}-storage
# gazdecki-consortium = "tenant-gazdecki-consortium-storage"

[development.auth0]
domain = "dev-5w5l8ake23bk7o4h.us.auth0.com"
audience = "https://legal-analyzer"
issuer = "https://dev-5w5l8ake23bk7o4h.us.auth0.com/"
client_id = "your-client-id"
client_secret = "your-client-secret"

[development.api]
auth0_webhook_key = "2ET1TpRKjEPd60cGgnN!" 