[production]
# Production environment overrides
debug = false
log_level = "WARNING"

# Central tenant database
[production.central_db]
host = "@format {env[DB_HOST]}"
port = "@format {env[DB_PORT]}"
database = "@format {env[DB_NAME]}"
username = "@format {env[DB_USER]}"
password = "@format {env[DB_PASSWORD]}"
connection_string = "@format postgresql://{env[DB_USER]}:{env[DB_PASSWORD]}@{env[DB_HOST]}:{env[DB_PORT]}/{env[DB_NAME]}"

# External services
[production.pinecone]
api_key = "@format {env[PINECONE_API_KEY]}"
region = "@format {env[PINECONE_REGION]}"

[production.azure]
service_bus_connection_string = "@format {env[AZURE_SERVICE_BUS_CONNECTION]}"
storage_connection_string = "@format {env[AZURE_STORAGE_CONNECTION]}" 