"""Initial tables for gazdecki_consortium

Revision ID: 4eed4cafdd30
Revises: 7fb3830eb5e0
Create Date: 2025-07-29 13:22:45.858046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4eed4cafdd30'
down_revision: Union[str, Sequence[str], None] = '7fb3830eb5e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
