"""Initial tables for gazdecki-consortium

Revision ID: 6f505a4d142e
Revises: b62f292dfb50
Create Date: 2025-07-28 21:03:12.196537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f505a4d142e'
down_revision: Union[str, Sequence[str], None] = 'b62f292dfb50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('document_type', sa.String(length=100), nullable=True))
    op.add_column('documents', sa.Column('classification_confidence', sa.Float(), nullable=True))
    op.add_column('documents', sa.Column('classification_candidates', sa.JSON(), nullable=True))
    op.add_column('documents', sa.Column('classification_summary', sa.Text(), nullable=True))
    op.add_column('documents', sa.Column('human_summary', sa.Text(), nullable=True))
    op.add_column('documents', sa.Column('text_extraction_result', sa.Text(), nullable=True))
    op.create_index(op.f('ix_documents_document_type'), 'documents', ['document_type'], unique=False)
    op.add_column('users', sa.Column('nextauth_user_id', sa.String(length=255), nullable=False))
    op.drop_index(op.f('ix_users_auth0_user_id'), table_name='users')
    op.create_index(op.f('ix_users_nextauth_user_id'), 'users', ['nextauth_user_id'], unique=True)
    op.drop_column('users', 'auth0_user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('auth0_user_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_users_nextauth_user_id'), table_name='users')
    op.create_index(op.f('ix_users_auth0_user_id'), 'users', ['auth0_user_id'], unique=True)
    op.drop_column('users', 'nextauth_user_id')
    op.drop_index(op.f('ix_documents_document_type'), table_name='documents')
    op.drop_column('documents', 'text_extraction_result')
    op.drop_column('documents', 'human_summary')
    op.drop_column('documents', 'classification_summary')
    op.drop_column('documents', 'classification_candidates')
    op.drop_column('documents', 'classification_confidence')
    op.drop_column('documents', 'document_type')
    # ### end Alembic commands ###
